/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.Schambes.Hangman.GUI.Registry;

import java.util.ArrayList;
import java.util.Collections;

import de.Schambes.Hangman.GUI.RegistryGUI;

/**
 *
 * @author Schambes
 */
@SuppressWarnings("serial")
public class PlayerRegistryGUI extends RegistryGUI {

    /**
     * Creates new form PlayerRegistry
     */
    public PlayerRegistryGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctrlPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        playerScrollPane = new javax.swing.JScrollPane();
        playerPanel = new javax.swing.JPanel();
        playerList = new ArrayList<de.Schambes.Hangman.GUI.Registry.PlayerGUI>();
        playerList.add(new de.Schambes.Hangman.GUI.Registry.PlayerGUI(this, playerList.size()));
        confirmPnl = new javax.swing.JPanel();
        continueBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(300, 230));

        addBtn.setText("Add Player");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ctrlPanelLayout = new javax.swing.GroupLayout(ctrlPanel);
        ctrlPanel.setLayout(ctrlPanelLayout);
        ctrlPanelLayout.setHorizontalGroup(
            ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ctrlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn)
                .addContainerGap())
        );
        ctrlPanelLayout.setVerticalGroup(
            ctrlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ctrlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        playerScrollPane.setMinimumSize(new java.awt.Dimension(280, 68));

        playerPanel.setLayout(new javax.swing.BoxLayout(playerPanel, javax.swing.BoxLayout.Y_AXIS));
        for(PlayerGUI p : playerList) {
        	playerPanel.add(p);
        }
        
        playerScrollPane.setViewportView(playerPanel);

        continueBtn.setText("Done");
        continueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        javax.swing.GroupLayout confirmPnlLayout = new javax.swing.GroupLayout(confirmPnl);
        confirmPnl.setLayout(confirmPnlLayout);
        confirmPnlLayout.setHorizontalGroup(
            confirmPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continueBtn)
                .addContainerGap())
        );
        confirmPnlLayout.setVerticalGroup(
            confirmPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(confirmPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(continueBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ctrlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctrlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueBtnActionPerformed
    	de.Schambes.Hangman.Player[] out = new de.Schambes.Hangman.Player[playerList.size()];
    	for(int i = 0; i < playerList.size(); i++) {
    		out[i] = playerList.get(i).getPlayer();
    	}
    	//TODO continue to next window
    }//GEN-LAST:event_continueBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        playerList.add(new de.Schambes.Hangman.GUI.Registry.PlayerGUI(this, playerList.size()));
    }//GEN-LAST:event_addBtnActionPerformed
    
    public void deletePlayer(int playerID) {
    	playerList.remove(playerID);
    	for(int i = playerID; i < playerList.size(); i++) {
    		playerList.get(i).setID(i);
    	}
    }
    
    //is called from Player object
    public void up(int playerID) {
    	if((playerID + 1) < playerList.size()) {
    		playerList.get(playerID).setID(playerID - 1);
    		playerList.get(playerID - 1).setID(playerID);
    		Collections.sort(playerList);
    	}
    }
    
    //is called from Player object
    public void down(int playerID) {
    	if((playerID) > 0) {
    		playerList.get(playerID).setID(playerID + 1);
    		playerList.get(playerID + 1).setID(playerID);
    		Collections.sort(playerList);
    	}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel confirmPnl;
    private javax.swing.JButton continueBtn;
    private javax.swing.JPanel ctrlPanel;
    private ArrayList<de.Schambes.Hangman.GUI.Registry.PlayerGUI> playerList;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JScrollPane playerScrollPane;
    // End of variables declaration//GEN-END:variables
}
